"""add diet questions to health_surveys

Revision ID: 16831bce556a
Revises: c3d4e5f6a7b8
Create Date: 2026-04-10 15:21:47.321535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16831bce556a'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_surveys', sa.Column('diet_q1', sa.Integer(), nullable=False))
    op.add_column('health_surveys', sa.Column('diet_q2', sa.Integer(), nullable=False))
    op.add_column('health_surveys', sa.Column('diet_q3', sa.Integer(), nullable=False))
    op.add_column('health_surveys', sa.Column('diet_q4', sa.Integer(), nullable=False))
    op.add_column('health_surveys', sa.Column('diet_q5', sa.Integer(), nullable=False))
    op.add_column('health_surveys', sa.Column('diet_q6', sa.Integer(), nullable=False))
    op.add_column('health_surveys', sa.Column('diet_q7', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_surveys', 'diet_q7')
    op.drop_column('health_surveys', 'diet_q6')
    op.drop_column('health_surveys', 'diet_q5')
    op.drop_column('health_surveys', 'diet_q4')
    op.drop_column('health_surveys', 'diet_q3')
    op.drop_column('health_surveys', 'diet_q2')
    op.drop_column('health_surveys', 'diet_q1')
    # ### end Alembic commands ###