"""init: 전체 모델 초기 마이그레이션

Revision ID: 7fe1494e2f2d
Revises:
Create Date: 2026-04-07 11:38:41.519978

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7fe1494e2f2d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("goals")
    op.drop_table("activity_logs")
    op.add_column("appointments", sa.Column("hospital_name", sa.String(length=100), nullable=False))
    op.add_column("appointments", sa.Column("visit_date", sa.DateTime(timezone=True), nullable=False))
    op.add_column("appointments", sa.Column("memo", sa.Text(), nullable=True))
    op.add_column("appointments", sa.Column("is_notified", sa.Boolean(), nullable=False))
    op.drop_column("appointments", "title")
    op.drop_column("appointments", "scheduled_at")
    op.drop_column("appointments", "notes")
    op.drop_column("appointments", "status")
    op.drop_column("appointments", "updated_at")
    op.drop_column("appointments", "doctor_name")
    op.drop_column("appointments", "location")
    op.add_column("medications", sa.Column("taken_today", sa.Boolean(), nullable=False))
    op.drop_column("medications", "updated_at")
    op.drop_column("medications", "is_taken")
    op.add_column("notification_settings", sa.Column("push_enabled", sa.Boolean(), nullable=False))
    op.add_column("notification_settings", sa.Column("appointment_reminder", sa.Boolean(), nullable=False))
    op.add_column("notification_settings", sa.Column("challenge_reminder", sa.Boolean(), nullable=False))
    op.add_column("notification_settings", sa.Column("weekly_report", sa.Boolean(), nullable=False))
    op.drop_column("notification_settings", "goal_notification")
    op.drop_column("notification_settings", "prediction_notification")
    op.drop_column("notification_settings", "challenge_notification")
    op.add_column("users", sa.Column("nickname", sa.String(length=20), nullable=False))
    op.add_column("users", sa.Column("is_onboarded", sa.Boolean(), nullable=False))
    op.drop_constraint(op.f("users_phone_number_key"), "users", type_="unique")
    op.drop_column("users", "last_login")
    op.drop_column("users", "gender")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "is_admin")
    op.drop_column("users", "name")
    op.drop_column("users", "birthday")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column("users", sa.Column("birthday", sa.DATE(), autoincrement=False, nullable=False))
    op.add_column("users", sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column("users", sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column("users", sa.Column("phone_number", sa.VARCHAR(length=11), autoincrement=False, nullable=False))
    op.add_column(
        "users", sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("gender", postgresql.ENUM("MALE", "FEMALE", name="gender"), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users", sa.Column("last_login", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_unique_constraint(
        op.f("users_phone_number_key"), "users", ["phone_number"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("users", "is_onboarded")
    op.drop_column("users", "nickname")
    op.add_column(
        "notification_settings", sa.Column("challenge_notification", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "notification_settings", sa.Column("prediction_notification", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "notification_settings", sa.Column("goal_notification", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_column("notification_settings", "weekly_report")
    op.drop_column("notification_settings", "challenge_reminder")
    op.drop_column("notification_settings", "appointment_reminder")
    op.drop_column("notification_settings", "push_enabled")
    op.add_column("medications", sa.Column("is_taken", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column(
        "medications", sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False)
    )
    op.drop_column("medications", "taken_today")
    op.add_column("appointments", sa.Column("location", sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column("appointments", sa.Column("doctor_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column(
        "appointments",
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column(
        "appointments",
        sa.Column(
            "status",
            postgresql.ENUM("SCHEDULED", "CANCELLED", "COMPLETED", name="appointmentstatus"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column("appointments", sa.Column("notes", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column(
        "appointments",
        sa.Column("scheduled_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    )
    op.add_column("appointments", sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column("appointments", "is_notified")
    op.drop_column("appointments", "memo")
    op.drop_column("appointments", "visit_date")
    op.drop_column("appointments", "hospital_name")
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("activity_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("activity_logs_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("activity_logs_pkey")),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("goals_user_id_fkey"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("goals_pkey")),
    )
    # ### end Alembic commands ###
