"""sync notification fields

Revision ID: ae700cd4eb74
Revises: 561f979d7636
Create Date: 2026-04-20 17:35:47.552902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae700cd4eb74'
down_revision: Union[str, None] = '561f979d7636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_settings', 'notification_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_settings', 'notification_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###