"""init

Revision ID: c3408253bb54
Revises:
Create Date: 2026-04-14 08:08:27.180104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3408253bb54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('required_logs', sa.Integer(), nullable=False),
    sa.Column('shap_feature', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('hospital_name', sa.String(length=100), nullable=False),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_surveys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('waist', sa.Float(), nullable=False),
    sa.Column('drinking', sa.String(length=10), nullable=False),
    sa.Column('drink_amount', sa.Float(), nullable=False),
    sa.Column('weekly_drink_freq', sa.Float(), nullable=False),
    sa.Column('monthly_binge_freq', sa.Float(), nullable=False),
    sa.Column('exercise', sa.String(length=10), nullable=False),
    sa.Column('weekly_exercise_count', sa.Integer(), nullable=False),
    sa.Column('smoking', sa.String(length=20), nullable=False),
    sa.Column('current_smoking', sa.String(length=10), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('sleep_disorder', sa.String(length=10), nullable=False),
    sa.Column('diet_q1', sa.Integer(), nullable=False),
    sa.Column('diet_q2', sa.Integer(), nullable=False),
    sa.Column('diet_q3', sa.Integer(), nullable=False),
    sa.Column('diet_q4', sa.Integer(), nullable=False),
    sa.Column('diet_q5', sa.Integer(), nullable=False),
    sa.Column('diet_q6', sa.Integer(), nullable=False),
    sa.Column('diet_q7', sa.Integer(), nullable=False),
    sa.Column('diet_score', sa.Integer(), nullable=False),
    sa.Column('diet_eval', sa.String(length=20), nullable=False),
    sa.Column('diabetes', sa.String(length=10), nullable=False),
    sa.Column('hypertension', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('medications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('schedule', sa.String(length=50), nullable=False),
    sa.Column('taken_today', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('appointment_reminder', sa.Boolean(), nullable=False),
    sa.Column('challenge_reminder', sa.Boolean(), nullable=False),
    sa.Column('weekly_report', sa.Boolean(), nullable=False),
    sa.Column('notification_time', sa.String(length=5), nullable=False),
    sa.Column('night_mode_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_action_reminder', sa.Boolean(), nullable=False),
    sa.Column('streak_reminder', sa.Boolean(), nullable=False),
    sa.Column('risk_change_alert', sa.Boolean(), nullable=False),
    sa.Column('goal_achievement_alert', sa.Boolean(), nullable=False),
    sa.Column('meal_reminder', sa.Boolean(), nullable=False),
    sa.Column('water_reminder', sa.Boolean(), nullable=False),
    sa.Column('alcohol_warning', sa.Boolean(), nullable=False),
    sa.Column('immediate_risk_alert', sa.Boolean(), nullable=False),
    sa.Column('challenge_fail_warning', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=False),
    sa.Column('character_state', sa.String(length=10), nullable=False),
    sa.Column('shap_factors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_challenges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_maintenance', sa.Boolean(), nullable=False),
    sa.Column('last_checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_challenge_id'], ['user_challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_logs')
    op.drop_table('user_challenges')
    op.drop_table('predictions')
    op.drop_table('notification_settings')
    op.drop_table('medications')
    op.drop_table('health_surveys')
    op.drop_table('appointments')
    op.drop_table('users')
    op.drop_table('challenges')