"""add push enabled notification fields

Revision ID: dd21ca24c87c
Revises: 728a9aedb732
Create Date: 2026-04-21 18:23:19.529565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd21ca24c87c"
down_revision: Union[str, None] = "728a9aedb732"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "notification_settings", sa.Column("push_enabled", sa.Boolean(), nullable=False, server_default="true")
    )
    op.add_column(
        "notification_settings", sa.Column("appointment_reminder", sa.Boolean(), nullable=False, server_default="true")
    )
    op.add_column(
        "notification_settings", sa.Column("weekly_report", sa.Boolean(), nullable=False, server_default="true")
    )
    op.add_column(
        "notification_settings", sa.Column("challenge_reminder", sa.Boolean(), nullable=False, server_default="true")
    )
    op.add_column(
        "notification_settings", sa.Column("daily_action_reminder", sa.Boolean(), nullable=False, server_default="true")
    )
    op.add_column(
        "notification_settings",
        sa.Column("goal_achievement_alert", sa.Boolean(), nullable=False, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification_settings", "goal_achievement_alert")
    op.drop_column("notification_settings", "daily_action_reminder")
    op.drop_column("notification_settings", "challenge_reminder")
    op.drop_column("notification_settings", "weekly_report")
    op.drop_column("notification_settings", "appointment_reminder")
    op.drop_column("notification_settings", "push_enabled")
    # ### end Alembic commands ###
